Fixup multiple inheritance issue with PySide6
Looks similar to https://bugreports.qt.io/browse/PYSIDE-1564 but happens on PySide 6.7...

Traceback (most recent call last):
  File "/home/julien/git/sgtk/tk-framework-desktopstartup/python/shotgun_desktop/startup.py", line 951, in main
    exit_code = __launch_app(app, splash, user, app_bootstrap, settings)
  File "/home/julien/git/sgtk/tk-framework-desktopstartup/python/shotgun_desktop/startup.py", line 425, in __launch_app
    engine = __start_engine_in_zero_config(app, app_bootstrap, splash, user)
  File "/home/julien/git/sgtk/tk-framework-desktopstartup/python/shotgun_desktop/startup.py", line 597, in __start_engine_in_zero_config
    return mgr.bootstrap_engine("tk-desktop")
  File "/home/julien/git/sgtk/tk-core/python/tank/bootstrap/manager.py", line 492, in bootstrap_engine
    engine = self._start_engine(tk, engine_name, entity)
  File "/home/julien/git/sgtk/tk-core/python/tank/bootstrap/manager.py", line 1217, in _start_engine
    engine = tank.platform.start_engine(engine_name, tk, ctx)
  File "/home/julien/.shotgun/julien.dev/sitec100.basic.desktop/cfg/install/core/python/tank/platform/engine.py", line 3044, in start_engine
    return _start_engine(engine_name, tk, None, context)
  File "/home/julien/.shotgun/julien.dev/sitec100.basic.desktop/cfg/install/core/python/tank/platform/engine.py", line 3204, in _start_engine
    engine = class_obj(tk, new_context, engine_name, env)
  File "/home/julien/git/sgtk/tk-desktop/engine.py", line 62, in __init__
    Engine.__init__(self, tk, *args, **kwargs)
  File "/home/julien/.shotgun/julien.dev/sitec100.basic.desktop/cfg/install/core/python/tank/platform/engine.py", line 172, in __init__
    self.init_engine()
  File "/home/julien/git/sgtk/tk-desktop/engine.py", line 142, in init_engine
    self.__impl = tk_desktop.get_engine_implementation(interface_type)(self)
  File "/home/julien/git/sgtk/tk-desktop/python/tk_desktop/desktop_engine_site_implementation.py", line 40, in __init__
    self.site_comm = SiteCommunication(engine)
  File "/home/julien/git/sgtk/tk-desktop/python/tk_desktop/site_communication.py", line 35, in __init__
    QtCore.QObject.__init__(self)
TypeError: CommunicationBase.__init__() missing 1 required positional argument: 'engine'