SG-39630 Make sure our datetime objects are created in naive mode (#199)
Make sure our datetime objects are created in naive mode

Critical since the info is then cached on disk in a string format
that does not include the timezone so, once they are loaded back
from disk, we have naive datetime  object.

Fixup regression introduced in #197:

  TypeError: can't compare offset-naive and offset-aware datetimes

* fixup! Make sure our datetime objects are created in naive mode